spring.application.name=lab_1
spring.datasource.url=jdbc:sqlite:src/main/resources/database.db
spring.datasource.driver-class-name=org.sqlite.JDBC
grpc.client.player-service.address=static://localhost:9090
grpc.client.player-service.negotiation-type=plaintext
server.port=8081